name: build-and-deploy
on:
  workflow_dispatch:
      
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "argosgroup/${{ env.REPOSITORY_NAME }}"

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Edit image on manifests repository
        env:
          IMAGE: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          echo "$IMAGE"