name: Snyk

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Paso siguiente de leer
        run: | 
          export LINEA=$(grep -m 1 "luuna/erpnext-worker:master-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          echo "LINEA=$LINEA" >> $GITHUB_ENV

      - name: Print IMAGE
        env:
          LINEA: ${{ env.LINEA }}
        run: |
          echo "Imagen encontrada: $LINEA"
          # Otra lógica utilizando $LINEA