name: Snyk
on:
  workflow_dispatch:
      
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        env:
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: "argosgroup/${{ env.REPOSITORY_NAME }}"
          
      - name: Build login 2
        run: docker login --password ${{ secrets.DOCKERHUB_TOKEN }}  --username ${{ secrets.DOCKERHUB_USER }} && docker images
      - name: Docker images list
        run: docker images

      - name: Build and push
        id: build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Edit image on manifests repository
        env:
          IMAGE: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          BRANCH: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          REPOSITORY_NAME: ${{ github.event.repository.name }}
        run: |
          echo "$IMAGE"

      - name: Run Snyk v2
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          IMAGE: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          # In order to use the Snyk Action you will need to have a Snyk API token.
          # More details in https://github.com/snyk/actions#gettin-your-snyk-token
          # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE }}
          args: --file=Dockerfile --exclude-base-image-vulns
          # - name: Upload result to GitHub Code Scanning
          #   uses: github/codeql-action/upload-sarif@v3
          #   with:
          #     sarif_file: snyk.sarif
  snyk:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t mcastellin/snyk-container-demo .
      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Run Snyk to check Docker image for vulnerabilities
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # More details in https://github.com/snyk/actions#gettin-your-snyk-token
        # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: argosgroup/test_snyk:main-5af43bfb72d4db32fc33ea04626d1c10bbba00e9
          args: --file=Dockerfile --exclude-base-image-vulns
        # - name: Upload result to GitHub Code Scanning
        #   uses: github/codeql-action/upload-sarif@v3
        #   with:
        #     sarif_file: snyk.sarif
      - name: Docker images list
        run: docker pull argosgroup/test_snyk:main-9da1c4424c64d49dcebfecc33a698be483df62dd
      - name: Docker images list
        run: docker images
      - name: Run Snyk v2
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
        # In order to use the Snyk Action you will need to have a Snyk API token.
        # More details in https://github.com/snyk/actions#gettin-your-snyk-token
        # or you can signup for free at https://snyk.io/login
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: argosgroup/test_snyk:main-9da1c4424c64d49dcebfecc33a698be483df62dd
          args: --file=Dockerfile --exclude-base-image-vulns
        # - name: Upload result to GitHub Code Scanning
        #   uses: github/codeql-action/upload-sarif@v3
        #   with:
        #     sarif_file: snyk.sarif