name: Validator

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  extract_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      IMAGE: ${{ steps.set_image.outputs.IMAGE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Check if test.yaml exists
        run: |
          if [ ! -f "test.yaml" ]; then
            echo "Error: test.yaml not found!"
            exit 1
          fi

      - name: Read line from file
        id: set_image
        run: | 
          export IMAGE=$(grep -m 1 "argosgroup/test_snyk:main-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          # Set output using set-output
          echo "::set-output name=IMAGE::$IMAGE"

  snyk-analysis:
    runs-on: ubuntu-latest
    needs: extract_image
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print image information
        env:
          IMAGE: ${{ needs.extract_image.outputs.IMAGE }}
        run: |
          echo "Image found: $IMAGE"

      - name: Pull Docker images list
        env:
          IMAGE: ${{ needs.extract_image.outputs.IMAGE }}
        run: docker pull ${{ env.IMAGE }}

      - name: Run Snyk
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.extract_image.outputs.IMAGE }}
          args: --file=Dockerfile --exclude-base-image-vulns

      - name: Upload results to GitHub Code Scanning
        run: cat snyk.sarif
