name: Snyk

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  extrac_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Paso siguiente de leer
        run: | 
          #export LINEA=$(grep -m 1 "luuna/erpnext-worker:master-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          export LINEA=$(grep -m 1 "argosgroup/test_snyk:main-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          echo "LINEA=$LINEA" >> $GITHUB_ENV

      - name: Print IMAGE
        env:
          LINEA: ${{ env.LINEA }}
        run: |
          echo "Imagen encontrada: $LINEA"
          # Otra lógica utilizando $LINEA
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker images list
        run: docker pull ${{ env.LINEA }}

      - name: Run Snyk v2
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          IMAGE: ${{ steps.meta.outputs.tags }}-${{ github.sha }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ env.IMAGE }}
          args: --file=Dockerfile --exclude-base-image-vulns
         