name: Validador

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  extrac_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      # Define una salida llamada 'IMAGE'
      IMAGE: ${{ steps.set_image.outputs.IMAGE }}
    steps:
      - name: Checkout código
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Leer línea desde archivo
        id: set_image
        run: | 
          export IMAGE=$(grep -m 1 "argosgroup/test_snyk:main-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          # Establecer la salida usando set-output
          echo "::set-output name=IMAGE::$IMAGE"

      - name: Imprimir información de la imagen
        env:
          IMAGE: ${{ env.IMAGE }}
        run: |
          echo "Imagen encontrada: $IMAGE"
          # Otra lógica utilizando $IMAGE
        id: image_id

  build:
    runs-on: ubuntu-latest
    needs: extrac_image
    timeout-minutes: 30
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Imprimir información de la imagen
        env:
          IMAGE: ${{ needs.extrac_image.outputs.IMAGE }}
        run: |
          echo "Imagen encontrada: $IMAGE"

      - name: Obtener lista de imágenes de Docker
        env:
          IMAGE: ${{ needs.extrac_image.outputs.IMAGE }}
        run: docker pull ${{ env.IMAGE }}

      - name: Ejecutar Snyk v2
        continue-on-error: true
        uses: snyk/actions/docker@v2
        env:
          IMAGE: ${{ needs.extrac_image.outputs.IMAGE }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.extrac_image.outputs.IMAGE }}
          args: --file=Dockerfile --exclude-base-image-vulns

      - name: Subir resultados a GitHub Code Scanning
        run: cat snyk.sarif
