name: Snyk
on:
  workflow_dispatch:
      
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
      
      - name: Paso siguiente de leer
        run:  | 
            linea=$(grep -m 1 "luuna/erpnext-worker:master-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
            echo $linea
          