name: Validador

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  extrac_image:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    outputs:
      # Define una salida llamada 'linea_output'
      linea_output: ${{ steps.set_linea.outputs.LINEA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: 'sagoyanfisic/test_snyk_yaml'
          ref: 'main'
          token: ${{ secrets.ACCESS_TOKEN }}
      
      - name: Paso siguiente de leer
        id: set_linea
        run: | 
          export LINEA=$(grep -m 1 "argosgroup/test_snyk:main-" test.yaml | sed 's/^[ \t]*//' |  awk '{print $2}' )
          echo "LINEA=$LINEA" >> $GITHUB_ENV
          # Establecer la salida usando set-output
          echo "::set-output name=LINEA::$LINEA"

      - name: Print IMAGE
        env:
          LINEA: ${{ env.LINEA }}
        run: |
          echo "Imagen encontrada: $LINEA"
          # Otra lógica utilizando $LINEA
        id: image_id

  build:
    runs-on: ubuntu-latest
    needs: extrac_image
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: DockerHub login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Print IMAGE
        env:
          LINEA: ${{ needs.extrac_image.outputs.linea_output }}
        run: |
          echo "Imagen encontrada: $LINEA"

      - name: Docker images list
        env:
          LINEA: ${{ needs.extrac_image.outputs.linea_output }}
        run: docker pull ${{ env.LINEA }}

      - name: Run Snyk v2
        continue-on-error: true
        uses: snyk/actions/docker@master
        env:
          IMAGE: ${{ needs.extrac_image.outputs.linea_output }}
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          image: ${{ needs.extrac_image.outputs.linea_output }}
          args: --file=Dockerfile --exclude-base-image-vulns
      - name: Upload result to GitHub Code Scanning
        run: cat snyk.sarif